<a href="https://colab.research.google.com/github/josemacoel/Evaluacion-5/blob/main/Actividad_5_P2_A01734153.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Actividad 5 | Parte 2**

### **José María Colombres Elguea**

### **Matrícula: A01734153**

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Etapa 2: Extracción de datos**

# **California_EUA**

In [261]:
california= pd.read_csv("California_EUA_LIMPIO.csv",encoding = "unicode_escape")
california.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6936 entries, 0 to 6935
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Ã¯Â»Â¿id                                      6936 non-null   float64
 1   host_id                                       6936 non-null   int64
 2   latitude                                      6936 non-null   float64
 3   longitude                                     6936 non-null   float64
 4   scrape_id                                     6936 non-null   float64
 5   host_listings_count                           6936 non-null   float64
 6   host_total_listings_count                     6936 non-null   float64
 7   accommodates                                  6936 non-null   float64
 8   bedrooms                                      6936 non-null   float64
 9   beds                                          6936 non-null   float64
 10  minimum_nights                                6936 non-null   float64
 11  maximum_nights                                6936 non-null   float64
 12  minimum_minimum_nights                        6936 non-null   float64
 13  maximum_minimum_nights                        6936 non-null   float64
 14  minimum_maximum_nights                        6936 non-null   float64
 15  maximum_maximum_nights                        6936 non-null   float64
 16  minimum_nights_avg_ntm                        6936 non-null   float64
 17  maximum_nights_avg_ntm                        6936 non-null   float64
 18  availability_30                               6936 non-null   int64
 19  availability_60                               6936 non-null   int64
 20  availability_90                               6936 non-null   int64
 21  availability_365                              6936 non-null   int64
 22  number_of_reviews                             6936 non-null   float64
 23  number_of_reviews_ltm                         6936 non-null   float64
 24  number_of_reviews_l30d                        6936 non-null   float64
 25  review_scores_rating                          6936 non-null   float64
 26  review_scores_accuracy                        6936 non-null   float64
 27  review_scores_cleanliness                     6936 non-null   float64
 28  review_scores_checkin                         6936 non-null   float64
 29  review_scores_communication                   6936 non-null   float64
 30  review_scores_location                        6936 non-null   float64
 31  review_scores_value                           6936 non-null   float64
 32  calculated_host_listings_count                6936 non-null   float64
 33  calculated_host_listings_count_entire_homes   6936 non-null   float64
 34  calculated_host_listings_count_private_rooms  6936 non-null   float64
 35  calculated_host_listings_count_shared_rooms   6936 non-null   float64
 36  reviews_per_month                             6936 non-null   float64
 37  listing_url                                   6936 non-null   object
 38  last_scraped                                  6936 non-null   object
 39  source                                        6936 non-null   object
 40  name                                          6936 non-null   object
 41  description                                   6936 non-null   object
 42  neighborhood_overview                         6936 non-null   object
 43  picture_url                                   6936 non-null   object
 44  host_url                                      6936 non-null   object
 45  host_name                                     6936 non-null   object
 46  host_since                                    6936 non-null   object
 47  host_location                                 6936 non-null   object
 48  host_about                                    6936 non-null   object
 49  host_response_time                            6936 non-null   object
 50  host_response_rate                            6936 non-null   object
 51  host_acceptance_rate                          6936 non-null   object
 52  host_is_superhost                             6936 non-null   object
 53  host_thumbnail_url                            6936 non-null   object
 54  host_picture_url                              6936 non-null   object
 55  host_neighbourhood                            6936 non-null   object
 56  host_verifications                            6936 non-null   object
 57  host_has_profile_pic                          6936 non-null   object
 58  host_identity_verified                        6936 non-null   object
 59  neighbourhood                                 6936 non-null   object
 60  neighbourhood_cleansed                        6936 non-null   object
 61  property_type                                 6936 non-null   object
 62  room_type                                     6936 non-null   object
 63  bathrooms_text                                6936 non-null   object
 64  amenities                                     6936 non-null   object
 65  price                                         6936 non-null   object
 66  has_availability                              6936 non-null   object
 67  calendar_last_scraped                         6936 non-null   object
 68  first_review                                  6936 non-null   object
 69  last_review                                   6936 non-null   object
 70  license                                       6936 non-null   object
 71  instant_bookable                              6936 non-null   object
dtypes: float64(32), int64(5), object(35)
memory usage: 3.8+ MB

## **a) host_acceptance_rate>50%**

Primero se realizó una limpieza de los datos, reemplazando los valores faltantes por 5%. Posteriormente se reemplazaron los valores tipo string y finalmente se realizó el filtro. Se puede observar que una mayoría de los datos coinciden con el criterio, siendo 5679 filas de 6936

In [254]:
california["host_acceptance_rate"] = california["host_acceptance_rate"].replace("No Data Available", "5%")
california['host_acceptance_rate'] = pd.to_numeric(california['host_acceptance_rate'].str.replace('%', ''))
acceptance = california[california["host_acceptance_rate"] > 50]
acceptance
acceptance.to_csv('filtroa_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,9.580000e+02,1169,37.770280,-122.433170,2.020000e+13,1.0,1.0,3.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$202.00,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,5.858000e+03,8904,37.744740,-122.420890,2.020000e+13,2.0,2.0,4.0,2.0,2.0,...,Entire home/apt,1 bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",$235.00,t,06/03/2023,03/05/2009,06/08/2017,No Data Available,f
2,8.142000e+03,21994,37.765550,-122.452130,2.020000e+13,13.0,14.0,1.0,1.0,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",$56.00,t,06/03/2023,08/09/2014,27/10/2022,No Data Available,f
4,8.739000e+03,7149,37.760300,-122.421970,2.020000e+13,2.0,2.0,3.0,1.0,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",$110.00,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
5,1.421770e+05,656263,37.784400,-122.479320,2.020000e+13,1.0,2.0,4.0,2.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$259.00,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6926,8.170000e+17,222540569,37.716070,-122.391170,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5 shared baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$83.00,t,06/03/2023,03/02/2023,25/02/2023,2022-012006STR,f
6927,8.170000e+17,486687635,37.788619,-122.422556,2.020000e+13,32.0,38.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",$80.00,t,06/03/2023,13/02/2023,13/02/2023,Exempt,f
6929,8.180000e+17,226555948,37.725231,-122.404776,2.020000e+13,5.3,7.7,2.0,1.0,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",$40.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6930,8.180000e+17,286802480,37.753771,-122.399004,2.020000e+13,6.0,10.0,1.0,1.0,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Security cameras on...",$56.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,t
6931,8.180000e+17,495900269,37.791994,-122.410000,2.020000e+13,9.0,9.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",$164.00,t,06/03/2023,No Data Available,No Data Available,147904,t

## **b) Sólo los registros con categoría super host**

En este codigo se realizó la búsqueda de aquellos valores con categoría super host, que estaban definidos con una t de true en la columna del propio nombre

In [262]:
super_host = california.loc[california['host_is_superhost'] == 't']
super_host
super_host.to_csv('filtrob_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,9.580000e+02,1169,37.770280,-122.433170,2.020000e+13,1.0,1.0,3.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$202.00,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
4,8.739000e+03,7149,37.760300,-122.421970,2.020000e+13,2.0,2.0,3.0,1.0,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",$110.00,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
7,1.053700e+04,36752,37.717500,-122.396980,2.020000e+13,2.0,3.0,2.0,1.0,1.0,...,Private room,1.5 shared baths,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",$95.00,t,06/03/2023,21/02/2010,28/01/2023,2022-011003STR,f
8,4.918670e+05,969518,37.771960,-122.434770,2.020000e+13,2.0,3.0,5.0,3.0,3.0,...,Entire home/apt,2 baths,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$425.00,t,06/03/2023,14/08/2012,19/02/2023,STR-0000192,f
9,1.442420e+05,699215,37.785460,-122.461480,2.020000e+13,2.0,2.0,6.0,3.0,3.0,...,Entire home/apt,2 baths,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",$545.00,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,8.160000e+17,36046172,37.719700,-122.463300,2.020000e+13,2.0,2.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Security cameras on property"", ""Self check-i...",$71.00,t,06/03/2023,09/02/2023,13/02/2023,1133735,f
6918,8.160000e+17,375566645,37.767920,-122.424256,2.020000e+13,23.0,26.0,1.0,1.0,1.0,...,Private room,1 shared bath,"[""Security cameras on property"", ""Self check-i...",$52.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6919,8.170000e+17,330231,37.803929,-122.443176,2.020000e+13,10.0,13.0,4.0,2.0,2.0,...,Entire home/apt,2 baths,"[""Oven"", ""Security cameras on property"", ""Cook...",$290.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,t
6923,8.170000e+17,4452428,37.784690,-122.392874,2.020000e+13,3.0,3.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",$110.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6929,8.180000e+17,226555948,37.725231,-122.404776,2.020000e+13,5.3,7.7,2.0,1.0,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",$40.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f

## **c) Los registros que no hallan verificado identidad “ not identity_verified”**

De la misma forma que el código anterior, se realizó un filtro que buscara aquellos registros que no tenian idetidad verificada.

In [263]:
not_identify = california.loc[california['host_identity_verified'] == 'f']
not_identify
not_identify.to_csv('filtroc_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
6,4.909310e+05,1269188,37.747660,-122.420410,2.020000e+13,1.0,3.0,2.0,1.0,1.0,...,Private room,1 bath,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",$100.00,t,06/03/2023,22/04/2014,26/11/2022,No Data Available,f
28,1.823100e+04,70224,37.749160,-122.429710,2.020000e+13,1.0,1.0,3.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",$95.00,t,06/03/2023,05/06/2010,19/06/2022,No Data Available,f
38,1.932920e+05,937281,37.751170,-122.425670,2.020000e+13,1.0,1.0,1.0,1.0,1.0,...,Private room,Half-bath,"[""Carbon monoxide alarm"", ""First aid kit"", ""Sm...",$120.00,t,06/03/2023,06/12/2011,22/09/2014,No Data Available,f
39,2.013130e+05,984585,37.803560,-122.404370,2.020000e+13,1.0,1.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$175.00,t,06/03/2023,17/05/2018,26/06/2021,No Data Available,f
71,2.311290e+05,1208533,37.792780,-122.410070,2.020000e+13,5.0,6.0,3.0,1.0,1.5,...,Entire home/apt,1 bath,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...","$1,000.00",t,06/03/2023,20/01/2012,23/10/2022,City Registration Pending,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6885,8.090000e+17,157999191,37.800850,-122.433658,2.020000e+13,24.0,24.0,1.0,1.0,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Lock on bedroom doo...",$75.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6905,8.130000e+17,240202942,37.731587,-122.496157,2.020000e+13,2.0,4.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Contact host body soap"", ""Security cameras o...",$76.00,t,06/03/2023,05/02/2023,28/02/2023,2022-013018STR,t
6931,8.180000e+17,495900269,37.791994,-122.410000,2.020000e+13,9.0,9.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",$164.00,t,06/03/2023,No Data Available,No Data Available,147904,t
6932,8.180000e+17,499392537,37.763060,-122.432023,2.020000e+13,1.0,1.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",$228.00,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,8.180000e+17,499294716,37.777633,-122.416478,2.020000e+13,1.0,1.0,1.0,1.0,1.0,...,Private room,1 shared bath,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",$104.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f

## **d) Los registros cuyo property_type = “Private room” y “Hotel room”**

En materia de filtros más específicos encontramos este, con un resultado de 4 filas que coinciden con la búsqueda de private room y hotel room.

In [255]:
property_type = california.loc[(california['property_type'] == 'Private room') | (california['property_type'] == 'Hotel room')]
property_type
property_type.to_csv('filtrod_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
7,10537.0,36752,37.71750,-122.39698,2.020000e+13,2.0,3.0,2.0,1.0,1.0,...,Private room,1.5 shared baths,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",$95.00,t,06/03/2023,21/02/2010,28/01/2023,2022-011003STR,f
1575,14305759.0,29483318,37.75145,-122.40719,2.020000e+13,3.0,3.0,2.0,1.0,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",$69.00,t,06/03/2023,11/08/2016,01/11/2020,City registration pending,t
2049,20957462.0,150732464,37.79586,-122.41915,2.020000e+13,7.0,9.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Free street parking"", ""Dishes and silverware...",$60.00,t,06/03/2023,09/12/2017,17/01/2023,No Data Available,t
4014,43477461.0,150732464,37.79525,-122.41931,2.020000e+13,7.0,9.0,1.0,1.0,1.0,...,Private room,1 bath,"[""Essentials"", ""Dishes and silverware"", ""Coffe...",$56.00,t,06/03/2023,28/02/2022,09/12/2022,No Data Available,f

## **e) Los registros que cuenten con bathroom > 1**

Al ser una columna en formato string este codigo fue más complejo. Primero se realizó la función unique() para mostrar los valores y así identificar cual texto equivalía a 1 o 0.5. Posteriormente se realizaron dos métodos, primero reemplazar los datos escritos por números en string y finalmente extraer dentro del string los dígitos.

In [251]:
california["bathrooms_text"].unique()

array(['1 bath', '4 shared baths', '1.5 baths', '1 private bath',
       '1.5 shared baths', '2 baths', 'No Data Available',
       '3 shared baths', 'Half-bath', '2 shared baths', '2.5 baths',
       '3 baths', '1 shared bath', '3.5 baths', 'Shared half-bath',
       '0 shared baths', 'Private half-bath', '0 baths',
       '10 shared baths', '10 baths', '4.5 baths', '4 baths',
       '2.5 shared baths', '5 shared baths', '8 shared baths',
       '6 shared baths', '3.5 shared baths', '5 baths',
       '6.5 shared baths', '5.5 baths', '6.5 baths', '8.5 baths',
       '6 baths'], dtype=object)

In [264]:
#cambiar Half-bath, Shared half-bath, Private half-bath, sin registro
california["bathrooms_text"] = california["bathrooms_text"].str.replace('Half-bath', '0.5').str.replace('Shared half-bath', '0.5').str.replace('Private half-bath', '0.5').str.replace('No Data Available', '0')

california["bathrooms_text"] = california["bathrooms_text"].str.extract('(\d+\.?\d*)', expand=False)
california["bathrooms_text"] = california["bathrooms_text"].astype(float)

bathroom = california[california["bathrooms_text"] > 1]
bathroom
bathroom.to_csv('filtroe_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,8.142000e+03,21994,37.765550,-122.452130,2.020000e+13,13.0,14.0,1.0,1.0,1.0,...,Private room,4.0,"[""Security cameras on property"", ""Host greets ...",$56.00,t,06/03/2023,08/09/2014,27/10/2022,No Data Available,f
3,8.339000e+03,24215,37.775640,-122.436420,2.020000e+13,2.0,6.0,4.0,2.0,2.0,...,Entire home/apt,1.5,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",$575.00,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
7,1.053700e+04,36752,37.717500,-122.396980,2.020000e+13,2.0,3.0,2.0,1.0,1.0,...,Private room,1.5,"[""Self check-in"", ""Shared BBQ grill: charcoal""...",$95.00,t,06/03/2023,21/02/2010,28/01/2023,2022-011003STR,f
8,4.918670e+05,969518,37.771960,-122.434770,2.020000e+13,2.0,3.0,5.0,3.0,3.0,...,Entire home/apt,2.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$425.00,t,06/03/2023,14/08/2012,19/02/2023,STR-0000192,f
9,1.442420e+05,699215,37.785460,-122.461480,2.020000e+13,2.0,2.0,6.0,3.0,3.0,...,Entire home/apt,2.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",$545.00,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6910,8.140000e+17,14649347,37.745091,-122.428807,2.020000e+13,1.0,2.0,5.0,3.0,1.5,...,Entire home/apt,3.0,"[""Oven"", ""Cooking basics"", ""Blender"", ""Cleanin...",$320.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6919,8.170000e+17,330231,37.803929,-122.443176,2.020000e+13,10.0,13.0,4.0,2.0,2.0,...,Entire home/apt,2.0,"[""Oven"", ""Security cameras on property"", ""Cook...",$290.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,t
6924,8.170000e+17,222540569,37.716079,-122.390953,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$79.00,t,06/03/2023,07/02/2023,07/02/2023,2022-012006STR,f
6925,8.170000e+17,222540569,37.716214,-122.391460,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$85.00,t,06/03/2023,10/02/2023,24/02/2023,2022-012006STR,f
6926,8.170000e+17,222540569,37.716070,-122.391170,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$83.00,t,06/03/2023,03/02/2023,25/02/2023,2022-012006STR,f

## **f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”**

Para este ejercicio de filtrado se encontraron 2 variables que coincidían con un precio mayor a $10,000 dólares y que fueran Entire Home. Se puede afirmar que son las casas más caras de este tipo.

In [265]:
california['price'] = california['price'].str.replace(',', '').str.replace('$', '').astype(float)
price = california.loc[(california['price'] > 10000) & (california['room_type'] == 'Entire home/apt')]
price
price.to_csv('filtrof_usa.csv', index=False)

<ipython-input-265-fba75d415fbe>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  california['price'] = california['price'].str.replace(',', '').str.replace('$', '').astype(float)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5759,6.430000e+17,32878131,37.732590,-122.43337,2.020000e+13,3.0,6.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",14000.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6490,7.860000e+17,91333416,37.781091,-122.47233,2.020000e+13,32.0,50.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Carbon monoxide alarm"", ""Hangers"", ""Iron"", ""...",25000.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,t

## **g) Los registros cuyo review_scores_cleanliness > 4.5**

Se encontró que una gran mayoría de los registros cumple con un review mayor a 4.5 para el score de cleanliness

In [266]:
review= california[california['review_scores_cleanliness'] > 4.5]
review
review.to_csv('filtrog_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,9.580000e+02,1169,37.770280,-122.433170,2.020000e+13,1.0,1.0,3.0,1.0,2.0,...,Entire home/apt,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",202.0,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
1,5.858000e+03,8904,37.744740,-122.420890,2.020000e+13,2.0,2.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Hange...",235.0,t,06/03/2023,03/05/2009,06/08/2017,No Data Available,f
2,8.142000e+03,21994,37.765550,-122.452130,2.020000e+13,13.0,14.0,1.0,1.0,1.0,...,Private room,4.0,"[""Security cameras on property"", ""Host greets ...",56.0,t,06/03/2023,08/09/2014,27/10/2022,No Data Available,f
3,8.339000e+03,24215,37.775640,-122.436420,2.020000e+13,2.0,6.0,4.0,2.0,2.0,...,Entire home/apt,1.5,"[""Oven"", ""Cooking basics"", ""TV"", ""Smoke alarm""...",575.0,t,06/03/2023,25/09/2009,28/06/2019,STR-0000264,f
4,8.739000e+03,7149,37.760300,-122.421970,2.020000e+13,2.0,2.0,3.0,1.0,1.0,...,Private room,1.0,"[""Paid parking garage off premises"", ""Luggage ...",110.0,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6931,8.180000e+17,495900269,37.791994,-122.410000,2.020000e+13,9.0,9.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Security cameras on property"", ""Self check-i...",164.0,t,06/03/2023,No Data Available,No Data Available,147904,t
6932,8.180000e+17,499392537,37.763060,-122.432023,2.020000e+13,1.0,1.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228.0,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f
6933,8.180000e+17,499294716,37.777633,-122.416478,2.020000e+13,1.0,1.0,1.0,1.0,1.0,...,Private room,1.0,"[""TV"", ""Free dryer â In unit"", ""Mountain vie...",104.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6934,8.180000e+17,485596413,37.738325,-122.396603,2.020000e+13,3.0,4.0,2.0,1.0,1.0,...,Private room,1.0,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",65.0,t,06/03/2023,No Data Available,No Data Available,2022-012562STR,f
6935,8.190000e+17,4836128,37.786442,-122.457006,2.020000e+13,2.0,4.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Carbon monoxide alarm"", ""Security cameras on...",375.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,t

## **h) Los registros cuyo review_scores_value > 4.9**

A partir de este ejercicio de filtrado se puede observar que muy pocos registros logran la excelencia en esta categoría de score.

In [267]:
review_scores= california[california['review_scores_value'] > 4.9]
review_scores
review_scores.to_csv('filtroh_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
9,1.442420e+05,699215,37.785460,-122.461480,2.020000e+13,2.0,2.0,6.0,3.0,3.0,...,Entire home/apt,2.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545.0,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
24,1.491080e+05,719538,37.762160,-122.450220,2.020000e+13,2.0,2.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Oven"", ""Security cameras on property"", ""Cook...",180.0,t,06/03/2023,01/08/2014,14/02/2023,No Data Available,f
26,1.252200e+04,18431,37.762370,-122.429920,2.020000e+13,1.0,2.0,2.0,1.0,1.0,...,Private room,1.5,"[""Essentials"", ""Bed linens"", ""Dishes and silve...",99.0,t,06/03/2023,14/01/2010,20/02/2023,STR-0000057,f
46,5.308570e+05,2607120,37.717270,-122.436440,2.020000e+13,2.0,3.0,1.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""S...",85.0,t,06/03/2023,20/05/2018,31/01/2023,STR-0003035,t
53,5.616020e+05,2760904,37.744030,-122.417550,2.020000e+13,1.0,1.0,2.0,2.0,2.0,...,Private room,1.0,"[""Oven"", ""Cooking basics"", ""Blender"", ""Shampoo...",80.0,t,06/03/2023,23/07/2012,01/03/2023,STR-0001006,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6920,8.170000e+17,407298390,37.801789,-122.426501,2.020000e+13,9.0,12.0,2.0,1.0,1.0,...,Private room,1.0,"[""Security cameras on property"", ""Self check-i...",107.0,t,06/03/2023,10/02/2023,10/02/2023,Exempt,t
6924,8.170000e+17,222540569,37.716079,-122.390953,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",79.0,t,06/03/2023,07/02/2023,07/02/2023,2022-012006STR,f
6925,8.170000e+17,222540569,37.716214,-122.391460,2.020000e+13,7.0,8.0,2.0,1.0,1.0,...,Private room,1.5,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",85.0,t,06/03/2023,10/02/2023,24/02/2023,2022-012006STR,f
6927,8.170000e+17,486687635,37.788619,-122.422556,2.020000e+13,32.0,38.0,2.0,1.0,1.0,...,Private room,1.0,"[""Security cameras on property"", ""Self check-i...",80.0,t,06/03/2023,13/02/2023,13/02/2023,Exempt,f
6932,8.180000e+17,499392537,37.763060,-122.432023,2.020000e+13,1.0,1.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Cooking basics"", ""Luggage dropoff allowed"", ...",228.0,t,06/03/2023,03/03/2023,03/03/2023,2023-001477STR,f

## **i) Los registros cuya availability_365< 100**

Se filtaron aquellos registros cuya disponibilidad anual es menor a 100 días

In [268]:
availability= california[california['availability_365'] < 100]
availability
availability.to_csv('filtroi_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
5,1.421770e+05,656263,37.784400,-122.479320,2.020000e+13,1.0,2.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",259.0,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
8,4.918670e+05,969518,37.771960,-122.434770,2.020000e+13,2.0,3.0,5.0,3.0,3.0,...,Entire home/apt,2.0,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",425.0,t,06/03/2023,14/08/2012,19/02/2023,STR-0000192,f
9,1.442420e+05,699215,37.785460,-122.461480,2.020000e+13,2.0,2.0,6.0,3.0,3.0,...,Entire home/apt,2.0,"[""Self check-in"", ""Cooking basics"", ""Shampoo"",...",545.0,t,06/03/2023,05/07/2011,02/01/2022,2022-011317STR,f
11,1.449780e+05,216682,37.792330,-122.424310,2.020000e+13,9.0,9.0,1.0,1.0,1.0,...,Private room,0.0,"[""Essentials"", ""Bed linens"", ""Carbon monoxide ...",55.0,t,06/03/2023,10/07/2011,28/02/2023,No Data Available,f
15,5.017700e+05,2475480,37.772520,-122.438460,2.020000e+13,5.0,5.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""TV with standard cable, DVD player, HBO Max""...",220.0,t,06/03/2023,27/06/2012,26/09/2022,No Data Available,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6913,8.160000e+17,36046172,37.719700,-122.463300,2.020000e+13,2.0,2.0,2.0,1.0,1.0,...,Private room,1.0,"[""Security cameras on property"", ""Self check-i...",71.0,t,06/03/2023,09/02/2023,13/02/2023,1133735,f
6917,8.160000e+17,45555637,37.748247,-122.433441,2.020000e+13,1.0,2.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Oven"", ""Security cameras on property"", ""Self...",222.0,t,06/03/2023,No Data Available,No Data Available,2023-001339STR,f
6918,8.160000e+17,375566645,37.767920,-122.424256,2.020000e+13,23.0,26.0,1.0,1.0,1.0,...,Private room,1.0,"[""Security cameras on property"", ""Self check-i...",52.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6923,8.170000e+17,4452428,37.784690,-122.392874,2.020000e+13,3.0,3.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Cooking basics"", ""Blender"", ""Shampoo"", ""TV"",...",110.0,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6931,8.180000e+17,495900269,37.791994,-122.410000,2.020000e+13,9.0,9.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Security cameras on property"", ""Self check-i...",164.0,t,06/03/2023,No Data Available,No Data Available,147904,t

## **j) Los registros cuya host_response_time sea “within an hour”**

Un porcentaje significativo de host responden dentro del marco de una hora, obteniendo 4221 filas de este filtro.

In [258]:
response= california[california['host_response_time'] == 'within an hour']
response
response.to_csv('filtroj_usa.csv', index=False)

,Ã¯Â»Â¿id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,9.580000e+02,1169,37.770280,-122.433170,2.020000e+13,1.0,1.0,3.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$202.00,t,06/03/2023,23/07/2009,19/02/2023,City Registration Pending,f
2,8.142000e+03,21994,37.765550,-122.452130,2.020000e+13,13.0,14.0,1.0,1.0,1.0,...,Private room,4 shared baths,"[""Security cameras on property"", ""Host greets ...",$56.00,t,06/03/2023,08/09/2014,27/10/2022,No Data Available,f
4,8.739000e+03,7149,37.760300,-122.421970,2.020000e+13,2.0,2.0,3.0,1.0,1.0,...,Private room,1 private bath,"[""Paid parking garage off premises"", ""Luggage ...",$110.00,t,06/03/2023,01/08/2009,25/02/2023,STR-0000028,f
5,1.421770e+05,656263,37.784400,-122.479320,2.020000e+13,1.0,2.0,4.0,2.0,2.0,...,Entire home/apt,1 bath,"[""Oven"", ""Self check-in"", ""Cooking basics"", ""L...",$259.00,t,06/03/2023,21/10/2011,17/02/2023,STR-0002192,f
12,4.938890e+05,2439917,37.728330,-122.441250,2.020000e+13,2.0,3.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Oven"", ""Cooking basics"", ""Shampoo"", ""Host gr...",$235.00,t,06/03/2023,17/06/2012,25/10/2022,STR-0004820,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6929,8.180000e+17,226555948,37.725231,-122.404776,2.020000e+13,5.3,7.7,2.0,1.0,1.0,...,Private room,1 shared bath,"[""Oven"", ""Security cameras on property"", ""Self...",$40.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,f
6930,8.180000e+17,286802480,37.753771,-122.399004,2.020000e+13,6.0,10.0,1.0,1.0,1.0,...,Private room,1 shared bath,"[""Carbon monoxide alarm"", ""Security cameras on...",$56.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,t
6931,8.180000e+17,495900269,37.791994,-122.410000,2.020000e+13,9.0,9.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Security cameras on property"", ""Self check-i...",$164.00,t,06/03/2023,No Data Available,No Data Available,147904,t
6934,8.180000e+17,485596413,37.738325,-122.396603,2.020000e+13,3.0,4.0,2.0,1.0,1.0,...,Private room,1 shared bath,"[""Essentials"", ""Carbon monoxide alarm"", ""Centr...",$65.00,t,06/03/2023,No Data Available,No Data Available,2022-012562STR,f
6935,8.190000e+17,4836128,37.786442,-122.457006,2.020000e+13,2.0,4.0,2.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Security cameras on...",$375.00,t,06/03/2023,No Data Available,No Data Available,No Data Available,t

# **Girona_España**

In [259]:
girona= pd.read_csv("Girona_España_LIMPIO.csv",encoding = "unicode_escape")
girona.info()

<ipython-input-259-65c35925bc1c>:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  girona= pd.read_csv("Girona_España_LIMPIO.csv",encoding = "unicode_escape")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19656 entries, 0 to 19655
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            19656 non-null  object
 1   host_id                                       19656 non-null  object
 2   latitude                                      19656 non-null  object
 3   longitude                                     19656 non-null  object
 4   scrape_id                                     19656 non-null  object
 5   host_listings_count                           19656 non-null  object
 6   host_total_listings_count                     19656 non-null  object
 7   accommodates                                  19656 non-null  object
 8   bedrooms                                      19656 non-null  object
 9   beds                                          19656 non-null  object
 10  minimum_nights                                19656 non-null  object
 11  maximum_nights                                19656 non-null  object
 12  minimum_minimum_nights                        19656 non-null  object
 13  maximum_minimum_nights                        19656 non-null  object
 14  minimum_maximum_nights                        19656 non-null  object
 15  maximum_maximum_nights                        19656 non-null  object
 16  minimum_nights_avg_ntm                        19656 non-null  object
 17  maximum_nights_avg_ntm                        19656 non-null  object
 18  availability_30                               19656 non-null  object
 19  availability_60                               19656 non-null  object
 20  availability_90                               19656 non-null  object
 21  availability_365                              19656 non-null  object
 22  number_of_reviews                             19656 non-null  object
 23  number_of_reviews_ltm                         19656 non-null  object
 24  number_of_reviews_l30d                        19655 non-null  float64
 25  review_scores_rating                          19655 non-null  float64
 26  review_scores_accuracy                        19655 non-null  float64
 27  review_scores_cleanliness                     19655 non-null  float64
 28  review_scores_checkin                         19655 non-null  float64
 29  review_scores_communication                   19655 non-null  float64
 30  review_scores_location                        19655 non-null  float64
 31  review_scores_value                           19655 non-null  float64
 32  calculated_host_listings_count                19655 non-null  float64
 33  calculated_host_listings_count_entire_homes   19655 non-null  float64
 34  calculated_host_listings_count_private_rooms  19655 non-null  float64
 35  calculated_host_listings_count_shared_rooms   19655 non-null  float64
 36  reviews_per_month                             19655 non-null  float64
 37  listing_url                                   19655 non-null  object
 38  last_scraped                                  19655 non-null  object
 39  source                                        19655 non-null  object
 40  name                                          19655 non-null  object
 41  description                                   19655 non-null  object
 42  neighborhood_overview                         19655 non-null  object
 43  picture_url                                   19655 non-null  object
 44  host_url                                      19655 non-null  object
 45  host_name                                     19655 non-null  object
 46  host_since                                    19655 non-null  object
 47  host_location                                 19655 non-null  object
 48  host_about                                    19655 non-null  object
 49  host_response_time                            19654 non-null  object
 50  host_response_rate                            19654 non-null  object
 51  host_acceptance_rate                          19654 non-null  object
 52  host_is_superhost                             19654 non-null  object
 53  host_thumbnail_url                            19654 non-null  object
 54  host_picture_url                              19654 non-null  object
 55  host_neighbourhood                            19654 non-null  object
 56  host_verifications                            19654 non-null  object
 57  host_has_profile_pic                          19654 non-null  object
 58  host_identity_verified                        19654 non-null  object
 59  neighbourhood                                 19654 non-null  object
 60  neighbourhood_cleansed                        19654 non-null  object
 61  property_type                                 19654 non-null  object
 62  room_type                                     19654 non-null  object
 63  bathrooms_text                                19654 non-null  object
 64  amenities                                     19654 non-null  object
 65  price                                         19654 non-null  object
 66  has_availability                              19654 non-null  object
 67  calendar_last_scraped                         19654 non-null  object
 68  first_review                                  19654 non-null  object
 69  last_review                                   19654 non-null  object
 70  license                                       19654 non-null  object
 71  instant_bookable                              19654 non-null  object
dtypes: float64(13), object(59)
memory usage: 10.8+ MB

In [212]:
girona["bathrooms_text"].unique()

array(['1 private bath', '1.5 shared baths', '1 bath', '2 baths',
       '4 baths', '4.5 baths', '2.5 baths', '3 baths', '6.5 baths',
       '1 shared bath', '1.5 baths', '3.5 baths', '3 shared baths',
       '7.5 baths', '6 baths', '8 baths', '5 baths', '7 baths',
       '8.5 baths', '10 baths', '5.5 baths', '2.5 shared baths',
       '5 shared baths', nan, '11 baths', '9.5 baths', '2 shared baths',
       '0 baths', '0 shared baths', '9 baths', '12 baths', 'Half-bath',
       '3.5 shared baths', '13 baths', '18 baths', 'No Data Available',
       '15.5 baths', '10.5 baths', '5.5 shared baths', 'Shared half-bath',
       '15 baths', '100 baths', '11.5 baths', '6 shared baths',
       '14.5 baths', '13.5 baths', '14 baths'], dtype=object)

## **a) host_acceptance_rate>50%**

Este filtro muestra aquellos registros con un host_acceptance mayor a 50%, obteniendo 17284 elementos que coinciden

In [260]:
girona["host_acceptance_rate"] = girona["host_acceptance_rate"].replace("No Data Available", "5%")
girona['host_acceptance_rate'] = pd.to_numeric(girona['host_acceptance_rate'].str.replace('%', ''))
acceptance = girona[girona["host_acceptance_rate"] > 50]
acceptance
acceptance.to_csv('filtroa_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,14551.0,57237,41.9965,2.83646,20230300000000.0,1.0,5.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",$42.00,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
2,1212820.0,6620645,42.11284,3.1667,20230300000000.0,2.0,3.0,4.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",$74.00,t,01/04/2023,10/06/2013,30/12/2022,No Data Available,f
3,751638.0,3680160,42.36958,2.9803,20230300000000.0,6.0,6.0,2.0,1.0,2.0,...,Private room,1 private bath,"[""Hair dryer"", ""Luggage dropoff allowed"", ""Fre...",$45.00,t,31/03/2023,23/08/2013,29/08/2022,PG000794,t
5,751997.0,3387407,41.91798,3.16419,20230300000000.0,12.0,12.0,4.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Pack ân play/Travel cr...",$105.00,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,752035.0,3387407,41.91801,3.17085,20230300000000.0,12.0,12.0,4.0,2.0,2.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",$110.00,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19648,858355000000000000.0,497533696,41.99906,3.19485,20230300000000.0,25.0,26.0,5.0,3.0,4.0,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",$136.00,t,01/04/2023,No Data Available,No Data Available,HUTG-037880,t
19649,858361000000000000.0,13308911,41.72036,2.92986,20230300000000.0,51.0,59.0,4.0,1.0,4.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",$107.00,t,01/04/2023,No Data Available,No Data Available,HUTG-027601,t
19651,858387000000000000.0,26281633,41.957265,3.201288,20230300000000.0,34.0,44.0,8.0,4.0,4.0,...,Entire home/apt,5 baths,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",$209.00,t,01/04/2023,No Data Available,No Data Available,HUTG-001292,t
19652,858396000000000000.0,444428600,41.69907,2.84408,20230300000000.0,3.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Pets allowed"", ""Washer""]",$52.00,t,01/04/2023,No Data Available,No Data Available,HUTG019727,t
19654,858418000000000000.0,389605038,41.809375,3.05391,20230300000000.0,111.0,121.0,4.0,2.0,3.0,...,Entire home/apt,1 bath,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",$108.00,t,01/04/2023,No Data Available,No Data Available,HUTG-065236,t

## **b) Sólo los registros con categoría super host**

El filtro muestra aquellos valores que tienen categoría super host, lo que es importante para observar el porcentaje de propiedades y titulares premium.

In [269]:
super_host = girona.loc[girona['host_is_superhost'] == 't']
super_host
#super_host.to_csv('filtrob_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,14551.0,57237,41.9965,2.83646,20230300000000.0,1.0,5.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",$42.00,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
8,45400.0,201228,41.95577,3.21096,20230300000000.0,1.0,2.0,4.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",$83.00,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
10,753604.0,3964191,41.7173,2.86409,20230300000000.0,7.0,7.0,6.0,3.0,4.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Free parking on pre...",$195.00,t,01/04/2023,08/09/2013,03/09/2022,LLG-000010,f
21,106704.0,553059,41.83631,2.937,20230300000000.0,5.0,10.0,5.0,4.0,3.7,...,Entire home/apt,4.5 baths,"[""Dedicated workspace"", ""Kitchen"", ""Self check...",$231.00,t,01/04/2023,19/07/2011,31/12/2022,PG-002599,f
23,766763.0,4043268,41.96041,3.22659,20230300000000.0,2.0,2.0,5.0,2.2,3.7,...,Entire home/apt,3 baths,"[""Carbon monoxide alarm"", ""Free parking on pre...",$399.00,t,01/04/2023,04/06/2016,16/10/2022,HUTG-043628,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19598,857006000000000000.0,137859766,42.29087,3.2764,20230300000000.0,15.0,25.0,6.0,3.0,4.0,...,Entire home/apt,3 baths,"[""Air conditioning"", ""Free parking on premises...",$341.00,t,01/04/2023,No Data Available,No Data Available,HUTG-060488,t
19602,856171000000000000.0,401533317,42.05427,3.20685,20230300000000.0,5.0,5.0,6.0,3.0,3.0,...,Entire home/apt,1.5 baths,"[""Refrigerator"", ""Microwave"", ""Safe"", ""Free st...",$230.00,t,01/04/2023,No Data Available,No Data Available,HUTG-059959,f
19618,857140000000000000.0,225125698,42.291029,3.278916,20230300000000.0,19.0,19.0,4.0,2.0,3.0,...,Entire home/apt,1 bath,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",$170.00,t,31/03/2023,No Data Available,No Data Available,HUTG-060928,t
19629,857697000000000000.0,125660503,41.78785,3.02869,20230300000000.0,10.0,13.0,6.0,3.0,3.0,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Free parking on premises...",$207.00,t,01/04/2023,No Data Available,No Data Available,HUTG-067564,t
19652,858396000000000000.0,444428600,41.69907,2.84408,20230300000000.0,3.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Pets allowed"", ""Washer""]",$52.00,t,01/04/2023,No Data Available,No Data Available,HUTG019727,t

## **c) Los registros que no hallan verificado identidad “ not identity_verified”**

A través de este filtrado se puede observar que la cantidad de registros que no han verificado su identidad es significativa, más del 10%

In [270]:
not_identify = girona.loc[girona['host_identity_verified'] == 'f']
not_identify
not_identify.to_csv('filtroc_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,1212820.0,6620645,42.11284,3.1667,20230300000000.0,2.0,3.0,4.0,1.0,2.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",$74.00,t,01/04/2023,10/06/2013,30/12/2022,No Data Available,f
7,1215790.0,3149645,41.84984,3.1265,20230300000000.0,1.0,1.0,7.0,3.0,5.0,...,Entire home/apt,2 baths,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",$60.00,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
9,1222762.0,6404885,42.21904,2.90744,20230300000000.0,1.0,1.0,5.0,3.0,4.0,...,Entire home/apt,2 baths,"[""Heating"", ""Kitchen"", ""Air conditioning"", ""Wa...",$65.00,t,31/03/2023,19/08/2013,14/09/2022,HUTG-012585,f
30,784892.0,4073860,42.39611,1.91888,20230300000000.0,1.0,5.0,6.0,3.0,7.0,...,Entire home/apt,3 baths,"[""Shared pool"", ""Free parking on premises"", ""R...",$100.00,t,31/03/2023,11/09/2015,11/09/2015,No Data Available,f
33,1242933.0,6774688,41.85578,3.13043,20230300000000.0,1.0,2.0,4.0,2.0,3.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Oven"", ""Dis...",$100.00,t,01/04/2023,02/08/2013,29/07/2019,HUTG-019098,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19554,856453000000000000.0,5113430,41.81861,3.056453,20230300000000.0,4.0,11.0,4.0,2.0,3.0,...,Entire home/apt,1.5 baths,"[""Air conditioning"", ""Stainless steel oven"", ""...",$182.00,t,01/04/2023,No Data Available,No Data Available,HUTG-029538,f
19561,855549000000000000.0,167394031,41.69185,2.81279,20230300000000.0,1.0,1.0,8.0,4.0,5.0,...,Entire home/apt,3 baths,"[""Free parking on premises"", ""Refrigerator"", ""...",$134.00,t,01/04/2023,No Data Available,No Data Available,HUTG002307,t
19562,856490000000000000.0,450603533,42.26445,3.1793,20230300000000.0,30.0,30.0,5.0,2.0,4.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",$168.00,t,01/04/2023,No Data Available,No Data Available,HUTG-023155,t
19612,857116000000000000.0,503009347,41.7945,3.04349,20230300000000.0,14.0,14.0,7.0,3.0,5.0,...,Entire home/apt,2 baths,"[""Iron"", ""Ethernet connection"", ""Single level ...",$161.00,t,01/04/2023,No Data Available,No Data Available,HUTG-008448,t
19613,857118000000000000.0,503009347,41.79446,3.04403,20230300000000.0,14.0,14.0,7.0,3.0,5.0,...,Entire home/apt,No Data Available,"[""Iron"", ""Dishwasher"", ""Washer"", ""Bathtub"", ""H...",$161.00,t,01/04/2023,No Data Available,No Data Available,HUTG-008448,t

## **d) Los registro cuyo property_type = “Private room” y “Hotel room”**

Una vez más, un filtro especializado mostrará muchos menos resultados, para Girona son 7

In [271]:
property_type = girona.loc[(girona['property_type'] == 'Private room') | (girona['property_type'] == 'Hotel room')]
property_type
property_type.to_csv('filtrod_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
356,3054347.0,15550598,42.28732,3.27713,20230300000000.0,2.0,2.0,2.0,2.0,1.0,...,Private room,1 private bath,"[""Air conditioning"", ""Refrigerator"", ""Shampoo""...",$109.00,t,01/04/2023,16/06/2014,05/11/2022,HUTG-002595,f
2485,14613107.0,38817324,42.15369,2.60122,20230300000000.0,1.0,1.0,4.0,1.0,2.0,...,Private room,1 bath,"[""Hair dryer"", ""Iron"", ""Washer"", ""Free parking...",$40.00,t,01/04/2023,02/10/2016,15/10/2017,No Data Available,f
3135,17117682.0,104655629,42.1448,2.56848,20230300000000.0,10.0,10.0,2.0,1.0,2.0,...,Private room,1 private bath,"[""Pool"", ""Pets allowed"", ""Hangers"", ""Heating"",...",$73.00,t,31/03/2023,25/02/2017,05/12/2022,ATG-000023,f
7839,32997174.0,248354355,42.15973,2.91132,20230300000000.0,1.0,3.0,2.0,1.0,1.0,...,Private room,1 bath,"[""Sanex body soap"", ""Microwave"", ""First aid ki...",$40.00,t,31/03/2023,16/08/2020,22/08/2022,Exempt,f
16666,658305000000000000.0,466301894,41.72831,2.919324,20230300000000.0,1.0,1.0,2.0,1.0,1.0,...,Private room,1.5 baths,"[""Carbon monoxide alarm"", ""Refrigerator"", ""Lon...",$50.00,t,01/04/2023,17/07/2022,22/07/2022,HUTB-123456,t
17058,686738000000000000.0,104927492,42.18328,2.88674,20230300000000.0,1.0,5.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Free parking on premises"", ""Shared outdoor p...",$120.00,t,31/03/2023,No Data Available,No Data Available,Exempt,f
19023,841209000000000000.0,162348326,42.30333,2.16657,20230300000000.0,2.0,2.0,2.0,1.0,1.0,...,Private room,1 private bath,"[""Clothing storage: walk-in closet"", ""Pack â...",$80.00,t,01/04/2023,No Data Available,No Data Available,Exempt,t

## **e) Los registros que cuenten con bathroom > 1**

Al ser una columna en formato string este codigo fue más complejo. Primero se realizó la función unique() para mostrar los valores y así identificar cual texto equivalía a 1 o 0.5. Posteriormente se realizaron dos métodos, primero reemplazar los datos escritos por números en string y finalmente extraer dentro del string los dígitos.

In [272]:
#cambiar Half-bath, Shared half-bath, Private half-bath, sin registro
girona["bathrooms_text"] = girona["bathrooms_text"].str.replace('Half-bath', '0.5').str.replace('Shared half-bath', '0.5').str.replace('Private half-bath', '0.5').str.replace('No Data Available', '0')

girona["bathrooms_text"] = girona["bathrooms_text"].str.extract('(\d+\.?\d*)', expand=False)
girona["bathrooms_text"] = girona["bathrooms_text"].astype(float)

bathroom = girona[girona["bathrooms_text"] > 1]
bathroom
bathroom.to_csv('filtroe_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
1,1205757.0,6586355,41.79304,2.77412,20230300000000.0,1.0,1.0,2.0,1.0,1.0,...,Private room,1.5,"[""Free parking on premises"", ""Refrigerator"", ""...",$47.00,t,31/03/2023,01/08/2013,26/06/2022,No Data Available,f
7,1215790.0,3149645,41.84984,3.1265,20230300000000.0,1.0,1.0,7.0,3.0,5.0,...,Entire home/apt,2.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",$60.00,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
9,1222762.0,6404885,42.21904,2.90744,20230300000000.0,1.0,1.0,5.0,3.0,4.0,...,Entire home/apt,2.0,"[""Heating"", ""Kitchen"", ""Air conditioning"", ""Wa...",$65.00,t,31/03/2023,19/08/2013,14/09/2022,HUTG-012585,f
11,48764.0,220145,42.17605,3.03974,20230300000000.0,1.0,2.0,8.0,4.0,5.0,...,Entire home/apt,2.0,"[""Refrigerator"", ""Long term stays allowed"", ""S...",$120.00,t,31/03/2023,04/06/2011,13/08/2022,HUTG-000207,f
14,1228453.0,6623729,42.24287,3.20562,20230300000000.0,1.0,1.0,5.0,2.0,4.0,...,Entire home/apt,2.0,"[""Beach essentials"", ""Board games"", ""Carbon mo...",$114.00,t,01/04/2023,12/05/2018,01/01/2023,HUTG-031144,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19642,857931000000000000.0,173153149,41.701663,2.870586,20230300000000.0,51.0,74.0,6.0,3.0,4.0,...,Entire home/apt,3.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",$440.00,t,01/04/2023,No Data Available,No Data Available,HUTG-023596,t
19643,857941000000000000.0,507641932,42.1817,3.10666,20230300000000.0,1.0,1.0,8.0,4.0,4.0,...,Entire home/apt,4.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",$450.00,t,01/04/2023,No Data Available,No Data Available,HUTB-449108,f
19644,857987000000000000.0,419014196,42.366939,3.161534,20230300000000.0,1.0,2.0,5.0,2.0,4.0,...,Entire home/apt,2.5,"[""Air conditioning"", ""Beach essentials"", ""Boar...",$100.00,t,01/04/2023,No Data Available,No Data Available,Exempt,f
19648,858355000000000000.0,497533696,41.99906,3.19485,20230300000000.0,25.0,26.0,5.0,3.0,4.0,...,Entire home/apt,2.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",$136.00,t,01/04/2023,No Data Available,No Data Available,HUTG-037880,t
19651,858387000000000000.0,26281633,41.957265,3.201288,20230300000000.0,34.0,44.0,8.0,4.0,4.0,...,Entire home/apt,5.0,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",$209.00,t,01/04/2023,No Data Available,No Data Available,HUTG-001292,t

## **f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”**

El filtro muestra los registros de tipo Entire Home mayores a $10,000 dólares para Girona

In [273]:
girona['price'] = girona['price'].str.replace(',', '').str.replace('$', '').astype(float)
price = girona.loc[(girona['price'] > 10000) & (girona['room_type'] == 'Entire home/apt')]
price
price.to_csv('filtrof_esp.csv', index=False)

<ipython-input-273-5a9b159d841e>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  girona['price'] = girona['price'].str.replace(',', '').str.replace('$', '').astype(float)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
753,4682669.0,24213114,42.053955,3.162875,20230300000000.0,2.0,2.0,5.0,2.2,3.7,...,Entire home/apt,8.0,"[""Beach essentials"", ""Board games"", ""Free park...",12986.0,t,01/04/2023,28/12/2015,26/12/2022,PG-000878,f
1841,11716662.0,10222076,41.89213,3.1846,20230300000000.0,1.0,1.0,4.0,3.0,3.0,...,Entire home/apt,1.5,"[""Changing table"", ""Fireplace guards"", ""Pack â...",14500.0,t,01/04/2023,14/07/2016,28/08/2022,No Data Available,f
3372,17726281.0,120856433,42.05615,2.64295,20230300000000.0,1.0,1.0,6.0,3.0,4.0,...,Entire home/apt,1.0,"[""Air conditioning"", ""Free parking on premises...",12977.0,t,31/03/2023,05/04/2017,12/03/2023,HUTG-025778,f
3932,18928661.0,129837136,41.84915,3.05936,20230300000000.0,28.0,73.0,6.0,3.0,4.0,...,Entire home/apt,2.0,"[""Sound system"", ""Refrigerator"", ""Valley view""...",20000.0,t,01/04/2023,No Data Available,No Data Available,HUTG-008573,t
3949,18928673.0,129837136,41.85659,3.04899,20230300000000.0,28.0,73.0,9.0,4.0,6.0,...,Entire home/apt,3.5,"[""Sound system"", ""Refrigerator"", ""Microwave"", ...",20000.0,t,01/04/2023,No Data Available,No Data Available,HUTG-008208,t
6633,26118654.0,122175936,42.28924,3.17472,20230300000000.0,26.4,33.9,8.0,4.0,6.0,...,Entire home/apt,3.0,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,No Data Available,No Data Available,HUTG-013538,t
6651,26146284.0,122175936,42.29,3.17656,20230300000000.0,26.4,33.9,5.0,2.2,7.0,...,Entire home/apt,4.0,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,No Data Available,No Data Available,HUTG-013538,t
7148,28483889.0,122175936,42.28965,3.17508,20230300000000.0,26.4,33.9,4.0,2.0,3.0,...,Entire home/apt,1.0,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,No Data Available,No Data Available,HUTG-013538,t
7542,31969327.0,129837136,41.86232,3.07854,20230300000000.0,28.0,73.0,8.0,4.0,4.0,...,Entire home/apt,3.0,"[""Harbor view"", ""Refrigerator"", ""Valley view"",...",20000.0,t,01/04/2023,No Data Available,No Data Available,HUTG-029082,t
9978,41784831.0,270230553,42.1936,3.02802,20230300000000.0,26.4,33.9,8.0,4.0,8.0,...,Entire home/apt,3.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",15960.0,t,31/03/2023,28/06/2020,05/09/2021,HUTG/028780,t

## **g) Los registros cuyo review_scores_cleanliness > 4.5**

Una gran cantidad de registros obtubieron una buena calificación para el score de limpieza

In [274]:
review= girona[girona['review_scores_cleanliness'] > 4.5]
review
review.to_csv('filtrog_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,14551.0,57237,41.9965,2.83646,20230300000000.0,1.0,5.0,2.0,1.0,1.0,...,Private room,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
1,1205757.0,6586355,41.79304,2.77412,20230300000000.0,1.0,1.0,2.0,1.0,1.0,...,Private room,1.5,"[""Free parking on premises"", ""Refrigerator"", ""...",47.0,t,31/03/2023,01/08/2013,26/06/2022,No Data Available,f
4,41342.0,180072,42.34655,3.20463,20230300000000.0,2.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",120.0,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
5,751997.0,3387407,41.91798,3.16419,20230300000000.0,12.0,12.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Air conditioning"", ""Pack ân play/Travel cr...",105.0,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,752035.0,3387407,41.91801,3.17085,20230300000000.0,12.0,12.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",110.0,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19651,858387000000000000.0,26281633,41.957265,3.201288,20230300000000.0,34.0,44.0,8.0,4.0,4.0,...,Entire home/apt,5.0,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",209.0,t,01/04/2023,No Data Available,No Data Available,HUTG-001292,t
19652,858396000000000000.0,444428600,41.69907,2.84408,20230300000000.0,3.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1.0,"[""Kitchen"", ""Pets allowed"", ""Washer""]",52.0,t,01/04/2023,No Data Available,No Data Available,HUTG019727,t
19653,858411000000000000.0,491503593,41.81372,3.064465,20230300000000.0,9.0,11.0,4.0,2.0,3.0,...,Entire home/apt,1.0,"[""Kitchen"", ""Free street parking"", ""Washer"", ""...",66.0,t,01/04/2023,No Data Available,No Data Available,HUTG-057830,f
19654,858418000000000000.0,389605038,41.809375,3.05391,20230300000000.0,111.0,121.0,4.0,2.0,3.0,...,Entire home/apt,1.0,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",108.0,t,01/04/2023,No Data Available,No Data Available,HUTG-065236,t
19655,858424000000000000.0,491503593,41.810169,3.066358,20230300000000.0,9.0,11.0,5.0,3.0,3.0,...,Entire home/apt,1.0,"[""Kitchen"", ""Washer"", ""Clothing storage"", ""Dis...",73.0,t,01/04/2023,No Data Available,No Data Available,HUTG-051787,f

## **h) Los registros cuyo review_scores_value > 4.9**

Pocos registros obtuvieron calificaciónes de excelencia en este parámetro

In [275]:
review_scores= girona[girona['review_scores_value'] > 4.9]
review_scores
review_scores.to_csv('filtroh_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
22,1234785.0,6732502,41.95188,3.20297,20230300000000.0,2.0,2.0,6.0,3.0,4.0,...,Entire home/apt,2.5,"[""Shared pool"", ""Free parking on premises"", ""R...",335.0,t,01/04/2023,30/08/2021,25/08/2022,HUTG-026895,f
26,774371.0,4085536,41.84428,3.10006,20230300000000.0,2.0,2.0,5.0,2.0,4.0,...,Entire home/apt,2.0,"[""Central air conditioning"", ""Refrigerator"", ""...",60.0,t,01/04/2023,22/01/2017,10/09/2022,HUTG-014853,f
40,1250062.0,6811852,41.82205,3.06874,20230300000000.0,1.0,1.0,8.0,4.0,6.0,...,Entire home/apt,2.5,"[""Shared pool"", ""Courtyard view"", ""Free parkin...",303.0,t,01/04/2023,03/08/2021,21/07/2022,HUTG-025234,f
43,809136.0,4208003,42.10369,3.0823,20230300000000.0,35.0,72.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",108.0,t,31/03/2023,09/04/2015,01/06/2019,HUTG-001370,t
53,1262051.0,6595329,42.20932,2.73697,20230300000000.0,7.0,7.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",73.0,t,31/03/2023,01/05/2016,04/11/2018,ATG-000053,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19039,841317000000000000.0,232395755,42.340474,1.9581,20230300000000.0,2.0,3.0,2.0,1.0,1.0,...,Entire home/apt,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",70.0,t,31/03/2023,26/03/2023,26/03/2023,HUTG-063362,f
19047,841674000000000000.0,253595964,42.252803,3.105931,20230300000000.0,2.0,2.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",59.0,t,01/04/2023,26/03/2023,26/03/2023,Exempt,t
19078,841996000000000000.0,38726312,42.24757,3.10449,20230300000000.0,2.0,2.0,2.0,1.0,1.0,...,Private room,1.0,"[""Hair dryer"", ""Dedicated workspace"", ""Air con...",39.0,t,01/04/2023,15/03/2023,15/03/2023,HUTG-047773,f
19203,842711000000000000.0,121671158,42.246529,3.127426,20230300000000.0,1.0,3.0,4.0,1.0,3.0,...,Entire home/apt,1.0,"[""Central air conditioning"", ""Refrigerator"", ""...",80.0,t,01/04/2023,12/03/2023,17/03/2023,HUTG-027175,f
19468,850041000000000000.0,505978243,41.974072,2.789637,20230300000000.0,1.0,1.0,3.0,1.0,1.0,...,Private room,1.0,"[""Dedicated workspace"", ""Mountain view"", ""Iron...",22.0,t,01/04/2023,23/03/2023,26/03/2023,HUTS-201920,t

## **i) Los registros cuya availability_365< 100**

Para este filtro se realizaon operaciones de replace, debido a que se encontró una fecha exacta dentro de la columna, así como datos str.

In [276]:
girona["availability_365"]=girona["availability_365"].replace("17/09/2022", 0)
girona['availability_365'] = girona['availability_365'].astype(float)
availability= girona[girona['availability_365'] < 100]
availability
availability.to_csv('filtroi_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
4,41342.0,180072,42.34655,3.20463,20230300000000.0,2.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1.0,"[""Free parking on premises"", ""Refrigerator"", ""...",120.0,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
7,1215790.0,3149645,41.84984,3.1265,20230300000000.0,1.0,1.0,7.0,3.0,5.0,...,Entire home/apt,2.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",60.0,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
11,48764.0,220145,42.17605,3.03974,20230300000000.0,1.0,2.0,8.0,4.0,5.0,...,Entire home/apt,2.0,"[""Refrigerator"", ""Long term stays allowed"", ""S...",120.0,t,31/03/2023,04/06/2011,13/08/2022,HUTG-000207,f
15,93343.0,477826,42.10405,3.14936,20230300000000.0,4.0,6.0,7.0,3.0,5.0,...,Entire home/apt,2.0,"[""Air conditioning"", ""Free parking on premises...",173.0,t,01/04/2023,No Data Available,No Data Available,HUTG-001447,f
20,1234784.0,6732502,41.95156,3.20217,20230300000000.0,2.0,2.0,2.0,1.0,1.0,...,Private room,1.0,"[""Shared pool"", ""Shampoo"", ""Host greets you"", ...",80.0,t,01/04/2023,08/07/2013,13/06/2021,HUTG-026895,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19628,857676000000000000.0,127955218,41.866532,3.069004,20230300000000.0,79.0,142.0,6.0,3.0,3.0,...,Entire home/apt,3.0,"[""Air conditioning"", ""Refrigerator"", ""Bidet"", ...",362.0,t,31/03/2023,No Data Available,No Data Available,HUTG-036943,t
19633,857770000000000000.0,127955218,41.779129,3.028061,20230300000000.0,79.0,142.0,6.0,3.0,4.0,...,Entire home/apt,2.0,"[""Air conditioning"", ""Free parking on premises...",349.0,t,01/04/2023,No Data Available,No Data Available,HUTG-000001,t
19635,857782000000000000.0,21668566,42.357181,3.167029,20230300000000.0,69.0,72.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Air conditioning"", ""Free parking on premises...",108.0,t,01/04/2023,No Data Available,No Data Available,HUTG-068543,t
19639,857858000000000000.0,461023346,41.973,3.17423,20230300000000.0,10.0,10.0,6.0,3.0,6.0,...,Entire home/apt,2.0,"[""Mountain view"", ""Kitchen"", ""Washer"", ""BBQ gr...",160.0,t,01/04/2023,No Data Available,No Data Available,HUTG-006876,f
19655,858424000000000000.0,491503593,41.810169,3.066358,20230300000000.0,9.0,11.0,5.0,3.0,3.0,...,Entire home/apt,1.0,"[""Kitchen"", ""Washer"", ""Clothing storage"", ""Dis...",73.0,t,01/04/2023,No Data Available,No Data Available,HUTG-051787,f

## **j) Los registros cuya host_response_time sea “within an hour”**

Una gran parte de propiedades tienen gran atención por parte del host, 12261 dentro del marco de una hora para Girona

In [277]:
response= girona[girona['host_response_time'] == 'within an hour']
response
#response.to_csv('filtroj_esp.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,14551.0,57237,41.9965,2.83646,20230300000000.0,1.0,5.0,2.0,1.0,1.0,...,Private room,1.0,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
5,751997.0,3387407,41.91798,3.16419,20230300000000.0,12.0,12.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Air conditioning"", ""Pack ân play/Travel cr...",105.0,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,752035.0,3387407,41.91801,3.17085,20230300000000.0,12.0,12.0,4.0,2.0,2.0,...,Entire home/apt,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",110.0,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
8,45400.0,201228,41.95577,3.21096,20230300000000.0,1.0,2.0,4.0,1.0,2.0,...,Entire home/apt,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",83.0,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
10,753604.0,3964191,41.7173,2.86409,20230300000000.0,7.0,7.0,6.0,3.0,4.0,...,Entire home/apt,1.0,"[""Carbon monoxide alarm"", ""Free parking on pre...",195.0,t,01/04/2023,08/09/2013,03/09/2022,LLG-000010,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19648,858355000000000000.0,497533696,41.99906,3.19485,20230300000000.0,25.0,26.0,5.0,3.0,4.0,...,Entire home/apt,2.0,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",136.0,t,01/04/2023,No Data Available,No Data Available,HUTG-037880,t
19649,858361000000000000.0,13308911,41.72036,2.92986,20230300000000.0,51.0,59.0,4.0,1.0,4.0,...,Entire home/apt,1.0,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",107.0,t,01/04/2023,No Data Available,No Data Available,HUTG-027601,t
19651,858387000000000000.0,26281633,41.957265,3.201288,20230300000000.0,34.0,44.0,8.0,4.0,4.0,...,Entire home/apt,5.0,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",209.0,t,01/04/2023,No Data Available,No Data Available,HUTG-001292,t
19652,858396000000000000.0,444428600,41.69907,2.84408,20230300000000.0,3.0,3.0,4.0,1.0,1.0,...,Entire home/apt,1.0,"[""Kitchen"", ""Pets allowed"", ""Washer""]",52.0,t,01/04/2023,No Data Available,No Data Available,HUTG019727,t
19654,858418000000000000.0,389605038,41.809375,3.05391,20230300000000.0,111.0,121.0,4.0,2.0,3.0,...,Entire home/apt,1.0,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",108.0,t,01/04/2023,No Data Available,No Data Available,HUTG-065236,t

# **DF_Mexico**

In [278]:
mexico= pd.read_csv("DF_Mexico_LIMPIO.csv")
mexico.info()

<ipython-input-278-e999d9b7f827>:1: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  mexico= pd.read_csv("DF_Mexico_LIMPIO.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24225 entries, 0 to 24224
Data columns (total 71 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            24224 non-null  float64
 1   host_id                                       24225 non-null  object
 2   latitude                                      24225 non-null  object
 3   longitude                                     24225 non-null  object
 4   scrape_id                                     24225 non-null  object
 5   host_listings_count                           24225 non-null  object
 6   host_total_listings_count                     24225 non-null  object
 7   accommodates                                  24225 non-null  object
 8   bedrooms                                      24225 non-null  object
 9   beds                                          24225 non-null  object
 10  minimum_nights                                24225 non-null  object
 11  maximum_nights                                24225 non-null  object
 12  minimum_minimum_nights                        24225 non-null  object
 13  maximum_minimum_nights                        24225 non-null  object
 14  minimum_maximum_nights                        24225 non-null  object
 15  maximum_maximum_nights                        24225 non-null  object
 16  minimum_nights_avg_ntm                        24225 non-null  object
 17  maximum_nights_avg_ntm                        24225 non-null  object
 18  availability_30                               24225 non-null  object
 19  availability_60                               24225 non-null  object
 20  availability_90                               24225 non-null  object
 21  availability_365                              24225 non-null  object
 22  number_of_reviews                             24225 non-null  object
 23  number_of_reviews_ltm                         24224 non-null  float64
 24  number_of_reviews_l30d                        24224 non-null  float64
 25  review_scores_rating                          24224 non-null  float64
 26  review_scores_accuracy                        24224 non-null  float64
 27  review_scores_cleanliness                     24224 non-null  float64
 28  review_scores_checkin                         24224 non-null  float64
 29  review_scores_communication                   24224 non-null  float64
 30  review_scores_location                        24224 non-null  float64
 31  review_scores_value                           24224 non-null  float64
 32  calculated_host_listings_count                24224 non-null  float64
 33  calculated_host_listings_count_entire_homes   24224 non-null  float64
 34  calculated_host_listings_count_private_rooms  24224 non-null  float64
 35  calculated_host_listings_count_shared_rooms   24224 non-null  float64
 36  reviews_per_month                             24224 non-null  float64
 37  listing_url                                   24224 non-null  object
 38  last_scraped                                  24224 non-null  object
 39  source                                        24224 non-null  object
 40  name                                          24224 non-null  object
 41  description                                   24224 non-null  object
 42  neighborhood_overview                         24224 non-null  object
 43  picture_url                                   24224 non-null  object
 44  host_url                                      24224 non-null  object
 45  host_name                                     24224 non-null  object
 46  host_since                                    24224 non-null  object
 47  host_location                                 24224 non-null  object
 48  host_about                                    24224 non-null  object
 49  host_response_time                            24223 non-null  object
 50  host_response_rate                            24223 non-null  object
 51  host_acceptance_rate                          24223 non-null  object
 52  host_is_superhost                             24223 non-null  object
 53  host_thumbnail_url                            24223 non-null  object
 54  host_picture_url                              24223 non-null  object
 55  host_neighbourhood                            24223 non-null  object
 56  host_verifications                            24223 non-null  object
 57  host_has_profile_pic                          24223 non-null  object
 58  host_identity_verified                        24223 non-null  object
 59  neighbourhood                                 24223 non-null  object
 60  neighbourhood_cleansed                        24223 non-null  object
 61  property_type                                 24223 non-null  object
 62  room_type                                     24223 non-null  object
 63  bathrooms_text                                24223 non-null  object
 64  amenities                                     24223 non-null  object
 65  price                                         24223 non-null  object
 66  has_availability                              24223 non-null  object
 67  calendar_last_scraped                         24223 non-null  object
 68  first_review                                  24223 non-null  object
 69  last_review                                   24223 non-null  object
 70  instant_bookable                              24223 non-null  object
dtypes: float64(15), object(56)
memory usage: 13.1+ MB

## **a) host_acceptance_rate>50%**

Para esta columna se realizó una limpieza de los datos, reemplazando los valores faltantes por 5%. Posteriormente se reemplazaron los valores tipo string y finalmente se realizó el filtro. Se puede observar que una mayoría de los datos coinciden con el criterio, siendo 20839 filas.

In [280]:
mexico["host_acceptance_rate"] = mexico["host_acceptance_rate"].replace("No Data Available", "5%")
mexico['host_acceptance_rate'] = pd.to_numeric(mexico['host_acceptance_rate'].str.replace('%', ''))
acceptance = mexico[mexico["host_acceptance_rate"] > 50]
acceptance
acceptance.to_csv('filtroa_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...","$1,469.00",t,2023-03-29,2012-10-31,2022-12-21,f
4,4.461600e+04,196253,19.41162,-99.17794,20230329041210,16.0,16.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...","$18,000.00",t,2023-03-30,2011-11-09,2023-03-26,f
5,2.075738e+06,2339771,19.41909,-99.16043,20230329041210,1.0,2.0,2.0,1.0,1.0,...,Entire loft,Entire home/apt,2 baths,"[""BBQ grill"", ""Luggage dropoff allowed"", ""TV w...","$2,561.00",t,2023-03-29,2014-02-05,2023-02-27,f
6,5.607400e+04,265650,19.43977,-99.15605,20230329041210,2.0,6.0,2.0,1.0,1.0,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",$650.00,t,2023-03-29,2011-04-02,2023-01-21,f
7,6.179200e+04,299558,19.41083,-99.18057,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...","$1,089.00",t,2023-03-30,2017-11-01,2022-12-31,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,8.539220e+17,506810572,19.385117,-99.117693,20230329041210,4.0,4.0,2.0,1.0,1.0,...,Private room in home,Private room,1 shared bath,"[""Wifi"", ""Washer"", ""Pets allowed"", ""Outdoor sh...",$251.00,t,2023-03-29,No Data Available,No Data Available,t
24220,8.539236e+17,488030249,19.396663,-99.148145,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",$760.00,t,2023-03-30,No Data Available,No Data Available,f
24222,8.542251e+17,154670560,19.371088,-99.190186,20230329041210,1.0,6.0,2.0,2.0,1.0,...,Private room in home,Private room,2.5 shared baths,"[""Luggage dropoff allowed"", ""Shared patio or b...",$533.00,t,2023-03-29,No Data Available,No Data Available,f
24223,8.542477e+17,7799414,19.403792,-99.164978,20230329041210,13.0,13.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...","$1,200.00",t,2023-03-30,No Data Available,No Data Available,t
24224,8.542603e+17,506864314,19.426283,-99.175603,20230329041210,2.0,2.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Long term stays allowed"", ""Cleaning products...","$1,720.00",t,2023-03-30,No Data Available,No Data Available,t

## **b) Sólo los registros con categoría super host**

El filtro muestra solo los registros  que coinciden con el parámetro super host

In [281]:
super_host = mexico.loc[mexico['host_is_superhost'] == 't']
super_host
super_host.to_csv('filtrob_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...","$1,469.00",t,2023-03-29,2012-10-31,2022-12-21,f
6,5.607400e+04,265650,19.43977,-99.15605,20230329041210,2.0,6.0,2.0,1.0,1.0,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",$650.00,t,2023-03-29,2011-04-02,2023-01-21,f
7,6.179200e+04,299558,19.41083,-99.18057,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...","$1,089.00",t,2023-03-30,2017-11-01,2022-12-31,f
8,7.047790e+05,2872228,19.43103,-99.14661,20230329041210,13.0,14.0,2.0,1.0,1.0,...,Entire condo,Entire home/apt,1 bath,"[""Ethernet connection"", ""TV with standard cabl...",$943.00,t,2023-03-29,2013-08-21,2023-02-27,f
9,7.283720e+05,3777702,19.44222,-99.14461,20230329041210,6.0,7.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""TV with standard cabl...","$2,561.00",t,2023-03-29,2012-10-31,2023-02-17,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24172,8.557745e+17,333035396,19.380398,-99.186986,20230329041210,5.3,6.2,6.0,2.0,1.6,...,Entire rental unit,Entire home/apt,2 baths,"[""Smoke alarm"", ""Single level home"", ""Long ter...","$1,226.00",t,2023-03-30,No Data Available,No Data Available,t
24180,8.560025e+17,10764020,19.432994,-99.196327,20230329041210,5.3,6.2,2.0,1.0,1.0,...,Entire serviced apartment,Entire home/apt,1 bath,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...","$2,382.00",t,2023-03-30,No Data Available,No Data Available,f
24192,8.561736e+17,420886866,19.446607,-99.157516,20230329041210,2.0,2.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Kitchen"", ""TV"", ""Carb...",$750.00,t,2023-03-30,No Data Available,No Data Available,f
24204,8.564998e+17,8905097,19.360038,-99.255523,20230329041210,5.3,6.2,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wifi"", ""Pets allowed"", ""Self ...","$2,179.00",t,2023-03-30,No Data Available,No Data Available,t
24223,8.542477e+17,7799414,19.403792,-99.164978,20230329041210,13.0,13.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Condit...","$1,200.00",t,2023-03-30,No Data Available,No Data Available,t

## **c) Los registros que no hallan verificado identidad “ not identity_verified”**

En un filtro parecido al anterior, se busco en la columna de identidad verificada aquellos valores marcados como f (false. Posteriormente se guardo el filtro en csv.

In [282]:
not_identify = mexico.loc[mexico['host_identity_verified'] == 'f']
not_identify
not_identify.to_csv('filtroc_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,2.056638e+06,10531228,19.35353,-99.16299,20230329041210,3.0,7.0,3.0,1.0,1.0,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...","$1,434.00",t,2023-03-30,2014-01-03,2018-06-24,f
21,1.316100e+05,647454,19.35416,-99.16488,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...","$1,244.00",t,2023-03-29,No Data Available,No Data Available,f
61,2.765040e+05,1444589,19.38061,-99.12729,20230329041210,1.0,1.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Elevator"", ""Wifi"", ""Washer"", ""Kitchen"", ""Poo...","$1,815.00",f,2023-03-30,No Data Available,No Data Available,f
68,2.918040e+05,1511568,19.36305,-99.15412,20230329041210,1.0,1.0,1.0,1.0,1.0,...,Private room in rental unit,Private room,1 bath,"[""Kitchen"", ""Smoking allowed"", ""Dryer"", ""Washer""]",$545.00,t,2023-03-30,No Data Available,No Data Available,f
70,2.988730e+05,1539548,19.43358,-99.14452,20230329041210,1.0,3.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2 baths,"[""Elevator"", ""Wifi"", ""Oven"", ""Iron"", ""Washer"",...","$1,362.00",t,2023-03-30,2012-04-19,2019-11-03,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23696,8.419651e+17,13667851,19.310823,-99.112738,20230329041210,2.0,2.0,1.0,1.0,1.0,...,Private room in home,Private room,1.5 shared baths,"[""Wifi"", ""Kitchen"", ""Lock on bedroom door"", ""H...",$240.00,t,2023-03-29,No Data Available,No Data Available,f
23874,8.485888e+17,487627497,19.423324,-99.160961,20230329041210,17.0,19.0,4.0,1.0,2.0,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...","$1,362.00",t,2023-03-30,No Data Available,No Data Available,t
23966,8.493108e+17,408076348,19.420921,-99.156091,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...","$5,200.00",f,2023-03-30,No Data Available,No Data Available,f
23967,8.493159e+17,408076348,19.42096,-99.15738,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...","$5,200.00",f,2023-03-30,No Data Available,No Data Available,f
23973,8.493187e+17,408076348,19.42085,-99.157242,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Private room in bed and breakfast,Private room,1 private bath,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...","$6,800.00",f,2023-03-30,No Data Available,No Data Available,f

## **d) Los registros cuyo property_type = “Private room” y “Hotel room”**

Como en los filtros de los dos df anteriores, al ser personalizado son pocas propiedades las que aparecen. El número de filas es proporcional pues el df de México es más grande.

In [283]:
property_type = mexico.loc[(mexico['property_type'] == 'Private room') | (mexico['property_type'] == 'Hotel room')]
property_type
property_type.to_csv('filtrod_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
21,1.316100e+05,647454,19.35416,-99.16488,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...","$1,244.00",t,2023-03-29,No Data Available,No Data Available,f
1062,1.227126e+07,2556582,19.39057309216409,-99.12979775702225,20230329041210,1.0,1.0,2.0,1.0,2.0,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",$748.00,t,2023-03-29,2017-05-23,2022-11-21,f
2670,1.963998e+07,136125882,19.34166,-99.15035,20230329041210,1.0,2.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Breakfast"", ""Washer"", ""Smoking allow...",$181.00,t,2023-03-29,2023-02-26,2023-02-26,t
2805,2.008928e+07,142841816,19.31152,-99.22341,20230329041210,1.0,1.0,2.0,1.0,2.0,...,Private room,Private room,2 shared baths,"[""Elevator"", ""Extra pillows and blankets"", ""Et...",$400.00,t,2023-03-29,2017-08-10,2023-03-07,t
3065,2.106790e+07,151816281,19.45733,-99.21227,20230329041210,2.0,2.0,2.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Smoke alarm"", ""Shared gym nearby"", ""Luggage ...",$600.00,t,2023-03-30,2017-12-12,2023-01-13,f
3257,2.176582e+07,158580118,19.43487,-99.18768,20230329041210,1.0,1.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Private entrance"", ""Wifi"", ""Washer"", ""Hanger...",$508.00,t,2023-03-30,2017-12-03,2023-03-19,t
3359,2.223018e+07,93911392,19.41364,-99.16292,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Single...",$765.00,t,2023-03-30,2017-12-23,2023-03-25,f
3372,2.224707e+07,93911392,19.41538,-99.16064,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""HDTV w...",$822.00,t,2023-03-30,2017-12-21,2023-03-19,f
3455,2.234015e+07,115584349,19.433,-99.14101,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Luggage dropoff allowed"", ""Dishes an...",$375.00,t,2023-03-30,2018-01-02,2021-11-27,f
3571,2.302637e+07,170856978,19.4369,-99.20763,20230329041210,1.0,2.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Elevator"", ""Smoke alarm"", ""Private entrance""...","$1,000.00",t,2023-03-30,No Data Available,No Data Available,t
3605,2.310080e+07,103716258,19.43409,-99.13191,20230329041210,1.0,1.0,2.9,3.0,1.6,...,Private room,Private room,6 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...","$27,435.00",t,2023-03-29,2019-03-23,2022-10-31,t
4303,2.586803e+07,34171966,19.34903,-99.16493,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Wifi"", ""Cooking basics"", ""Iron"", ""Washer"", ""...",$526.00,t,2023-03-30,2018-07-02,2023-03-27,t
5667,3.182698e+07,185535296,19.33975,-99.20108,20230329041210,7.0,10.0,1.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Wifi"", ""Hangers"", ""Essentials""]",$579.00,t,2023-03-29,2019-02-25,2022-05-20,t
6244,3.305132e+07,245350245,19.44535,-99.21863,20230329041210,4.0,8.0,2.9,1.0,1.6,...,Private room,Private room,1 private bath,"[""Luggage dropoff allowed"", ""Long term stays a...","$1,757.00",t,2023-03-29,2019-03-24,2022-11-27,t
11128,4.700766e+07,345395010,19.40288,-99.13481,20230329041210,2.0,5.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Private entrance"", ""W...",$320.00,t,2023-03-30,2021-06-29,2023-02-27,t
11920,4.904509e+07,133609729,19.37162,-99.16179,20230329041210,2.0,2.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Hot water"", ""Essenti...",$450.00,t,2023-03-30,2022-05-01,2022-11-20,f
12299,5.010668e+07,290843938,19.39061,-99.18114,20230329041210,4.0,5.0,2.0,1.0,2.0,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...",$339.00,t,2023-03-29,2021-12-05,2023-03-23,f
12712,5.079634e+07,2518152,19.45877,-99.17539,20230329041210,8.0,8.0,2.0,1.0,1.0,...,Private room,Private room,1.5 shared baths,"[""Free street parking"", ""BBQ grill"", ""Luggage ...",$750.00,t,2023-03-29,2022-01-20,2022-01-20,t
12841,5.089396e+07,411507264,19.453215,-99.181328,20230329041210,1.0,1.0,1.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Private outdoor kitchen"", ""Ho...","$1,081.00",t,2023-03-29,2021-11-08,2023-02-24,t
12864,5.116439e+07,161016544,19.41581,-99.16108,20230329041210,2.0,2.0,1.0,1.0,1.0,...,Private room,Private room,3.5 shared baths,"[""City skyline view"", ""Long term stays allowed...",$364.00,t,2023-03-30,2021-08-06,2023-01-25,t
13674,5.255737e+07,93911392,19.41534,-99.16228,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",$640.00,t,2023-03-30,2021-10-17,2023-03-12,f
13675,5.255777e+07,93911392,19.41334,-99.16086,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",$733.00,t,2023-03-30,2021-10-15,2023-03-26,f
13681,5.255802e+07,93911392,19.41389,-99.1629,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",$712.00,t,2023-03-30,2021-10-14,2023-03-19,f
13714,5.253658e+07,93911392,19.41382,-99.1627,20230329041210,28.0,6.2,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",$739.00,t,2023-03-30,2021-10-14,2023-02-28,f
14805,5.380559e+07,248524358,19.38331,-99.16172,20230329041210,6.0,6.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Free street parking"",...",$514.00,t,2023-03-30,2022-08-31,2022-08-31,f
14919,5.410629e+07,438593737,19.3548,-99.16817,20230329041210,4.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Cleaning available dur...","$1,491.00",t,2023-03-30,2022-01-12,2022-06-26,t
15031,5.419477e+07,282436180,19.45267,-99.05569,20230329041210,2.0,2.0,1.0,3.0,1.0,...,Private room,Private room,1 shared bath,"[""BBQ grill"", ""HDTV with Netflix"", ""Cleaning p...",$400.00,t,2023-03-29,No Data Available,No Data Available,f
15093,5.421577e+07,439419001,19.37657,-99.16506,20230329041210,2.0,2.0,1.0,1.0,1.0,...,Private room,Private room,1.5 baths,"[""Stainless steel oven"", ""Free street parking""...",$450.00,t,2023-03-30,2022-02-04,2022-05-03,f
15358,5.530831e+17,438593737,19.3563,-99.16654,20230329041210,4.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Free street parking"", ...","$1,491.00",t,2023-03-30,2022-02-10,2022-11-13,t
16017,5.886911e+17,400461338,19.37866,-99.16659,20230329041210,4.0,18.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Luggage dropoff allow...",$771.00,t,2023-03-30,2022-03-26,2023-01-01,f
16935,6.260308e+17,66387078,19.430712,-99.163963,20230329041210,5.3,32.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",$243.00,t,2023-03-29,2022-05-23,2023-03-10,t
16936,6.260436e+17,66387078,19.43176,-99.16445,20230329041210,5.3,32.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",$234.00,t,2023-03-29,2022-05-31,2023-02-27,t
17155,6.383222e+17,283357024,19.42988,-99.153091,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Laguna Cyprien shampoo"", ""Luggage dropoff al...","$3,000.00",t,2023-03-30,No Data Available,No Data Available,f
17252,6.456595e+17,463433619,19.41896,-99.15701,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...","$1,800.00",t,2023-03-30,2022-07-18,2022-07-18,f
18955,7.012631e+17,248524358,19.384375,-99.160576,20230329041210,6.0,6.0,1.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",$900.00,t,2023-03-30,2022-12-15,2022-12-15,f
19584,7.286389e+17,49926105,19.35469,-99.14286,20230329041210,3.0,3.0,3.0,1.0,1.0,...,Private room,Private room,Private half-bath,"[""Free street parking"", ""BBQ grill"", ""Luggage ...","$1,486.00",t,2023-03-29,No Data Available,No Data Available,f
19758,7.332723e+17,972988,19.44418,-99.16079,20230329041210,3.0,8.0,2.0,1.0,1.0,...,Private room,Private room,1.5 shared baths,"[""Wifi"", ""Patio or balcony"", ""Washer"", ""City s...",$600.00,t,2023-03-30,2022-11-02,2023-03-21,t
19921,7.415339e+17,450807747,19.38386,-99.17638,20230329041210,1.0,1.0,2.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",$402.00,t,2023-03-29,2022-10-23,2023-02-04,f
20377,7.574503e+17,438549721,19.38062,-99.193048,20230329041210,4.0,7.0,1.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Stainless steel oven"", ""Luggage dropoff allo...",$220.00,t,2023-03-30,2022-12-06,2023-01-07,t
20857,7.668923e+17,488289168,19.42993,-99.16546,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Security cameras on ...",$450.00,t,2023-03-30,2022-12-17,2023-03-23,t
20859,7.689874e+17,212991892,19.37823,-99.16797,20230329041210,4.0,18.0,2.0,1.0,1.0,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Luggage dropoff allow...",$600.00,t,2023-03-30,2023-02-25,2023-03-14,t
20865,7.668960e+17,488289168,19.429477,-99.166558,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Security cameras on ...",$500.00,t,2023-03-30,2023-01-28,2023-02-19,t
22716,8.212247e+17,248524358,19.385389,-99.159992,20230329041210,6.0,6.0,2.0,1.0,1.0,...,Private room,Private room,1 bath,"[""Ethernet connection"", ""Free street parking"",...",$529.00,t,2023-03-30,No Data Available,No Data Available,t

## **e) Los registros que cuenten con bathroom > 1**

Se realizó el mismo procedimiento de limpieza que para los archivos de California y Girona, reemplazando valores y extrayendo el string correspondiente. Se pudo observar que en México muchos registros cuentan con bastantes baños, llegando hasta 15.

In [279]:
mexico["bathrooms_text"].unique()

array(['1.5 baths', '1 bath', '2 baths', '5.5 baths', '1 shared bath',
       '1 private bath', '3 baths', '5 baths', '1.5 shared baths',
       '2.5 baths', '4.5 baths', '6 baths', '3.5 baths',
       'No Data Available', '2 shared baths', '3 shared baths',
       '2.5 shared baths', 'Half-bath', '8 shared baths',
       '4 shared baths', '4 baths', '10 baths', '16 baths',
       '3.5 shared baths', '5 shared baths', '7 baths', '20 baths',
       '4.5 shared baths', '0 shared baths', '0 baths', '50 baths',
       '10 shared baths', '8.5 baths', '9 baths', '7.5 baths',
       '11.5 baths', '8 baths', 'Shared half-bath', '14 baths',
       '6 shared baths', '11 baths', '6.5 baths', nan, '15 baths',
       '13 baths', 'Private half-bath', '15 shared baths',
       '12 shared baths', '9.5 baths', '9 shared baths'], dtype=object)

In [284]:
#cambiar Half-bath, Shared half-bath, Private half-bath, sin registro
mexico["bathrooms_text"] = mexico["bathrooms_text"].str.replace('Half-bath', '0.5').str.replace('Shared half-bath', '0.5').str.replace('Private half-bath', '0.5').str.replace('No Data Available', '0')

mexico["bathrooms_text"] = mexico["bathrooms_text"].str.extract('(\d+\.?\d*)', expand=False)
mexico["bathrooms_text"] = mexico["bathrooms_text"].astype(float)

bathroom = mexico[mexico["bathrooms_text"] > 1]
bathroom
bathroom.to_csv('filtroe_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,2.056638e+06,10531228,19.35353,-99.16299,20230329041210,3.0,7.0,3.0,1.0,1.0,...,Entire loft,Entire home/apt,1.5,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...","$1,434.00",t,2023-03-30,2014-01-03,2018-06-24,f
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...","$1,469.00",t,2023-03-29,2012-10-31,2022-12-21,f
4,4.461600e+04,196253,19.41162,-99.17794,20230329041210,16.0,16.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5,"[""Free street parking"", ""Security cameras on p...","$18,000.00",t,2023-03-30,2011-11-09,2023-03-26,f
5,2.075738e+06,2339771,19.41909,-99.16043,20230329041210,1.0,2.0,2.0,1.0,1.0,...,Entire loft,Entire home/apt,2.0,"[""BBQ grill"", ""Luggage dropoff allowed"", ""TV w...","$2,561.00",t,2023-03-29,2014-02-05,2023-02-27,f
9,7.283720e+05,3777702,19.44222,-99.14461,20230329041210,6.0,7.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5,"[""Free street parking"", ""TV with standard cabl...","$2,561.00",t,2023-03-29,2012-10-31,2023-02-17,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24195,8.564566e+17,499836247,19.414209,-99.162285,20230329041210,6.0,6.0,6.0,2.0,3.0,...,Entire rental unit,Entire home/apt,2.0,"[""Dedicated workspace"", ""Smoke alarm"", ""Wifi"",...","$2,367.00",t,2023-03-30,No Data Available,No Data Available,t
24197,8.564611e+17,396911095,19.449712,-99.219327,20230329041210,1.0,2.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,2.0,"[""Smoke alarm"", ""BBQ grill"", ""Wine glasses"", ""...",$748.00,t,2023-03-30,No Data Available,No Data Available,f
24207,8.565133e+17,445250346,19.419651,-99.16457,20230329041210,4.0,4.0,6.0,3.0,1.6,...,Entire home,Entire home/apt,2.0,"[""Stainless steel oven"", ""Ethernet connection""...","$3,240.00",t,2023-03-30,No Data Available,No Data Available,t
24211,8.536914e+17,155903047,19.434576,-99.173216,20230329041210,1.0,1.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2.5,"[""Wifi"", ""Fire extinguisher"", ""Kitchen"", ""TV"",...","$1,741.00",t,2023-03-30,No Data Available,No Data Available,t
24222,8.542251e+17,154670560,19.371088,-99.190186,20230329041210,1.0,6.0,2.0,2.0,1.0,...,Private room in home,Private room,2.5,"[""Luggage dropoff allowed"", ""Shared patio or b...",$533.00,t,2023-03-29,No Data Available,No Data Available,f

## **f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”**

Se encontraron solo 9 casas que coinciden con el filtro. Al ser un mercado con menor economía, hay menos casas de forma proporcional en México que sobrepasan los $10,000 dólares.

In [285]:
mexico['price'] = mexico['price'].str.replace(',', '').str.replace('$', '').astype(float)
price = mexico.loc[(girona['price'] > 10000) & (mexico['room_type'] == 'Entire home/apt')]
price
price.to_csv('filtrof_mex.csv', index=False)

<ipython-input-285-5f1cde82e9e4>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  mexico['price'] = mexico['price'].str.replace(',', '').str.replace('$', '').astype(float)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
753,8.842643e+06,18281799,19.345,-99.12348,20230329041210,1.0,1.0,4.0,2.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Wifi"", ""Washer"", ""Pets allowed"", ""Kitchen"", ...",998.0,f,2023-03-30,No Data Available,No Data Available,f
1841,1.641796e+07,44203755,19.39927,-99.17322,20230329041210,2.0,2.0,6.0,2.0,3.0,...,Entire rental unit,Entire home/apt,1.0,"[""Free street parking"", ""Long term stays allow...",908.0,t,2023-03-30,2017-01-04,2020-03-09,f
3932,2.425622e+07,182398028,19.29492,-99.04021,20230329041210,11.0,11.0,6.0,2.0,1.6,...,Entire home,Entire home/apt,1.0,"[""Luggage dropoff allowed"", ""Long term stays a...",600.0,t,2023-03-29,2018-05-07,2022-12-18,f
6651,3.512140e+07,257686655,19.44349,-99.20322,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.5,"[""Elevator"", ""Smoke alarm"", ""Wifi"", ""Washer"", ...",1400.0,t,2023-03-30,No Data Available,No Data Available,t
7148,3.702326e+07,267983259,19.41063,-99.16199,20230329041210,5.3,6.2,2.0,1.0,1.0,...,Entire loft,Entire home/apt,1.0,"[""Dedicated workspace"", ""Smoke alarm"", ""Privat...",1180.0,t,2023-03-30,2019-07-28,2023-03-22,t
7542,3.790970e+07,276377520,19.40994,-99.178,20230329041210,5.3,6.2,4.0,1.0,2.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1750.0,t,2023-03-30,2019-09-07,2023-03-02,f
9978,4.480195e+07,357701035,19.4218,-99.1687,20230329041210,5.3,31.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Private entrance"", ""Wifi"", ""Iron"", ""Washer"",...",992.0,t,2023-03-29,2020-08-16,2023-02-05,f
19453,7.246346e+17,46957511,19.44066,-99.18073,20230329041210,2.0,8.0,7.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""Samsun...",2499.0,t,2023-03-30,No Data Available,No Data Available,f
19456,7.216716e+17,473157296,19.418957,-99.174829,20230329041210,4.0,4.0,4.0,2.0,2.0,...,Entire serviced apartment,Entire home/apt,1.0,"[""Stainless steel oven"", ""BBQ grill"", ""Luggage...",2307.0,t,2023-03-29,2022-10-20,2023-03-09,t

## **g) Los registros cuyo review_scores_cleanliness > 4.5**

La gran mayoría de los registros cumplen con el parámetro. Puede ser debido a que en México el contacto entre el host y su propiedad es más cercano.

In [286]:
review= mexico[mexico['review_scores_cleanliness'] > 4.5]
review
review.to_csv('filtrog_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,2.056638e+06,10531228,19.35353,-99.16299,20230329041210,3.0,7.0,3.0,1.0,1.0,...,Entire loft,Entire home/apt,1.5,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,2023-03-30,2014-01-03,2018-06-24,f
1,2.072354e+06,16840050,19.35358,-99.16948,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Entire guest suite,Entire home/apt,1.0,"[""Free street parking"", ""Cleaning products"", ""...",830.0,t,2023-03-30,2014-01-01,2022-11-04,f
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,2023-03-29,2012-10-31,2022-12-21,f
3,3.579700e+04,153786,19.38283,-99.27178,20230329041210,1.0,1.0,2.0,1.0,1.0,...,Entire villa,Entire home/apt,1.0,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,2023-03-29,No Data Available,No Data Available,f
4,4.461600e+04,196253,19.41162,-99.17794,20230329041210,16.0,16.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5,"[""Free street parking"", ""Security cameras on p...",18000.0,t,2023-03-30,2011-11-09,2023-03-26,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24220,8.539236e+17,488030249,19.396663,-99.148145,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",760.0,t,2023-03-30,No Data Available,No Data Available,f
24221,8.539667e+17,506816029,19.392023,-99.118722,20230329041210,1.0,1.0,7.0,2.0,3.0,...,Entire rental unit,Entire home/apt,1.0,"[""Lake access"", ""Ski-in/Ski-out"", ""Wifi"", ""Out...",1520.0,t,2023-03-29,No Data Available,No Data Available,t
24222,8.542251e+17,154670560,19.371088,-99.190186,20230329041210,1.0,6.0,2.0,2.0,1.0,...,Private room in home,Private room,2.5,"[""Luggage dropoff allowed"", ""Shared patio or b...",533.0,t,2023-03-29,No Data Available,No Data Available,f
24223,8.542477e+17,7799414,19.403792,-99.164978,20230329041210,13.0,13.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,2023-03-30,No Data Available,No Data Available,t
24224,8.542603e+17,506864314,19.426283,-99.175603,20230329041210,2.0,2.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,1.0,"[""Long term stays allowed"", ""Cleaning products...",1720.0,t,2023-03-30,No Data Available,No Data Available,t

## **h) Los registros cuyo review_scores_value > 4.9**

El review de score con alta calificación es menor en proporción a los otros dataframes de Girona y California

In [287]:
review_scores= mexico[mexico['review_scores_value'] > 4.9]
review_scores
review_scores.to_csv('filtroh_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
10,2.083241e+06,8282570,19.4153,-99.16763,20230329041210,7.0,7.0,3.0,1.0,2.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1881.0,t,2023-03-30,2014-10-03,2023-03-13,f
11,6.770300e+04,334451,19.41152,-99.16857,20230329041210,3.0,5.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1.0,"[""Record player"", ""Extra pillows and blankets""...",2088.0,t,2023-03-30,2011-11-17,2023-01-01,f
13,7.064400e+04,212109,19.35448,-99.16217,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Free street parking"", ""Luggag...",1097.0,t,2023-03-29,2012-02-14,2023-01-31,f
24,7.830800e+05,1767559,19.33009,-99.21418,20230329041210,3.0,3.0,1.0,1.0,1.0,...,Private room in home,Private room,1.5,"[""Extra pillows and blankets"", ""Wifi"", ""Iron"",...",549.0,t,2023-03-29,2015-06-26,2023-03-26,f
26,2.118573e+06,10802698,19.38777,-99.17532,20230329041210,3.0,3.0,6.0,3.0,1.6,...,Entire rental unit,Entire home/apt,3.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,2023-03-30,2014-01-31,2023-03-02,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24058,8.527679e+17,10059555,19.423503,-99.16535,20230329041210,2.0,2.0,5.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2.0,"[""Ethernet connection"", ""Smoke alarm"", ""BBQ gr...",1800.0,t,2023-03-30,2023-03-24,2023-03-24,f
24059,8.527835e+17,263823796,19.43405,-99.14772,20230329041210,3.0,3.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Hot water kettle"", ""Luggage d...",925.0,t,2023-03-29,2023-03-24,2023-03-24,f
24110,8.530664e+17,406773068,19.407758,-99.1353,20230329041210,1.0,1.0,3.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1.5,"[""Free street parking"", ""Conditioner"", ""Single...",750.0,t,2023-03-29,2023-03-26,2023-03-26,f
24128,8.531385e+17,257870736,19.411143,-99.163152,20230329041210,1.0,2.0,1.0,1.0,1.0,...,Private room in home,Private room,1.5,"[""Wifi"", ""Paid parking on premises"", ""Washer"",...",250.0,t,2023-03-30,2023-03-26,2023-03-26,t
24189,8.560973e+17,484538652,19.41407,-99.177642,20230329041210,12.0,12.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Co...",891.0,t,2023-03-30,2023-03-29,2023-03-29,t

## **i) Los registros cuya availability_365< 100**

Este filtro muestra la disponibilidad durante el año menor a 100, lo que puede indicar las propiedades con mayor movimiento y ocupación. En México es comín que se utilicen por temporadas.

In [288]:
mexico["availability_365"]=mexico["availability_365"].replace('2023-03-05', 0)
mexico['availability_365'] = mexico['availability_365'].astype(float)
availability= mexico[mexico['availability_365'] < 100]
availability
availability.to_csv('filtroi_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,2023-03-29,2012-10-31,2022-12-21,f
21,1.316100e+05,647454,19.35416,-99.16488,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Private room,Private room,1.0,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,2023-03-29,No Data Available,No Data Available,f
26,2.118573e+06,10802698,19.38777,-99.17532,20230329041210,3.0,3.0,6.0,3.0,1.6,...,Entire rental unit,Entire home/apt,3.0,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,2023-03-30,2014-01-31,2023-03-02,f
37,1.870300e+05,899360,19.41057,-99.1773,20230329041210,6.0,8.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",50000.0,t,2023-03-30,2011-11-01,2023-03-15,f
38,1.877450e+05,899360,19.41057,-99.1773,20230329041210,6.0,8.0,3.0,1.0,2.0,...,Entire loft,Entire home/apt,2.0,"[""Wifi"", ""Washer"", ""Free street parking"", ""Hos...",5000.0,t,2023-03-30,2013-11-10,2018-01-03,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24160,8.557070e+17,3394561,19.429353,-99.147642,20230329041210,2.0,6.0,2.0,1.0,1.0,...,Private room in rental unit,Private room,1.0,"[""Free street parking"", ""Hot water kettle"", ""L...",444.0,t,2023-03-29,No Data Available,No Data Available,t
24166,8.573027e+17,227002676,19.425988,-99.175245,20230329041210,5.3,6.2,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2.0,"[""Single level home"", ""Long term stays allowed...",3001.0,t,2023-03-30,No Data Available,No Data Available,t
24171,8.573031e+17,227002676,19.424015,-99.174396,20230329041210,5.3,6.2,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,2.0,"[""Single level home"", ""Long term stays allowed...",3001.0,t,2023-03-30,No Data Available,No Data Available,t
24187,8.560964e+17,2086889,19.411379,-99.171272,20230329041210,1.0,1.0,5.0,2.0,1.6,...,Entire rental unit,Entire home/apt,2.5,"[""Stainless steel oven"", ""Smoke alarm"", ""55\"" ...",1477.0,t,2023-03-30,No Data Available,No Data Available,f
24194,8.564462e+17,3240358,19.41337,-99.173447,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Wifi"", ""Washer"", ""BBQ grill"",...",2130.0,t,2023-03-30,No Data Available,No Data Available,f

## **j) Los registros cuya host_response_time sea “within an hour”**

El filtro muestra una cantidad importante de registros donde el host responde en el marco de una hora, comprobando la hipoteis de que posiblemente en México el contacto con el host es más directo

In [289]:
response= mexico[mexico['host_response_time'] == 'within an hour']
response
response.to_csv('filtroj_mex.csv', index=False)

,id,host_id,latitude,longitude,scrape_id,host_listings_count,host_total_listings_count,accommodates,bedrooms,beds,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,6.960370e+05,3531879,19.4418,-99.18402,20230329041210,4.0,4.0,6.0,3.0,3.0,...,Entire rental unit,Entire home/apt,2.0,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,2023-03-29,2012-10-31,2022-12-21,f
4,4.461600e+04,196253,19.41162,-99.17794,20230329041210,16.0,16.0,2.9,1.4,1.6,...,Entire home,Entire home/apt,5.5,"[""Free street parking"", ""Security cameras on p...",18000.0,t,2023-03-30,2011-11-09,2023-03-26,f
6,5.607400e+04,265650,19.43977,-99.15605,20230329041210,2.0,6.0,2.0,1.0,1.0,...,Entire condo,Entire home/apt,1.0,"[""Luggage dropoff allowed"", ""Long term stays a...",650.0,t,2023-03-29,2011-04-02,2023-01-21,f
7,6.179200e+04,299558,19.41083,-99.18057,20230329041210,2.0,3.0,2.0,1.0,1.0,...,Private room in home,Private room,1.0,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,2023-03-30,2017-11-01,2022-12-31,f
8,7.047790e+05,2872228,19.43103,-99.14661,20230329041210,13.0,14.0,2.0,1.0,1.0,...,Entire condo,Entire home/apt,1.0,"[""Ethernet connection"", ""TV with standard cabl...",943.0,t,2023-03-29,2013-08-21,2023-02-27,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24215,8.537247e+17,62835605,19.421104,-99.159691,20230329041210,1.0,1.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Hot water kettle"", ""Conditioner"", ""Cleaning ...",1120.0,t,2023-03-30,No Data Available,No Data Available,t
24217,8.537793e+17,504610517,19.417178,-99.169791,20230329041210,2.0,2.0,4.0,2.0,2.0,...,Entire rental unit,Entire home/apt,1.0,"[""Wifi"", ""Paid parking on premises"", ""Washer"",...",853.0,t,2023-03-30,No Data Available,No Data Available,f
24218,8.537903e+17,29239005,19.41121,-99.174161,20230329041210,3.0,3.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Clothing storage: closet and dresser"", ""Smok...",980.0,t,2023-03-29,No Data Available,No Data Available,t
24220,8.539236e+17,488030249,19.396663,-99.148145,20230329041210,3.0,4.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Wifi"", ""Iron"", ""Washer"", ""Sel...",760.0,t,2023-03-30,No Data Available,No Data Available,f
24223,8.542477e+17,7799414,19.403792,-99.164978,20230329041210,13.0,13.0,2.0,1.0,1.0,...,Entire rental unit,Entire home/apt,1.0,"[""Smoke alarm"", ""Free street parking"", ""Condit...",1200.0,t,2023-03-30,No Data Available,No Data Available,t